= Setting up a user account and logging in
:docinfo: shared
:toc: auto
:nofooter:
:markup-in-source: attributes+

This page describes how to create a user account and log in to use the API.

== Overview

We use EMBL-EBI's {aapServerRootURL}[Authentication, authorisation and profile (AAP)] service to get information
about who you are and what data you are allowed to access.

This page is intended to supplement the {aapServerAPIRootURL}/docs[API documentation] provided by AAP, highlighting
the steps necessary to use AAP with the submission API. Please see the AAP web pages for further details.

We use token based authentication. This means that once you have an account, you can login with your username and password
to receive a https://jwt.io/[token]. This is a piece of text that contains all the information we need to know who you
are and what data you are allowed to access. You present this information to the API every time you make a request.

The tokens last for 1 hour, so if you have a long running process you may find the token expires.

== Creating your account

You can create an account through the {aapServerRootURL}/registerUser[AAP webpage], or through their API.

AAP supports two types of accounts - those created within the AAP system, and Elixir single-sign-on (SSO) accounts (log
in with a google, ORCID or LinkedIn account, or your research insitute). We can work with with either account type, but
there is not currently any way to get an AAP token through their API while using an Elixir SSO account. Therefore we
recommend that programatic users create AAP accounts.

== How to get a token

You can obtain a AAP token by executing the following curl command.

=== Example request

[source,bash,subs={markup-in-source}]
----
 $ curl -u <your_aap_username>:<your_aap_password> {aapServerAPIRootURL}/auth
----
The response will contains your AAP token.

=== Example response

....
eyJhbGciOiWerFg78ghY.eyJpc3MiOiJodHRwhdsL3RzaS5lYmkuYWMudWsiLCJleHAiOjE1MDc4MjIxNzEsImp0aSI6IlNWUndCYWlubTA1MFlEZHJaWFRMbWciLCJpYXQiOjE1MDc4MTg1NzEsInN1YiI6InVzci0wZmRhM2YzZS0wM2I1LTQzOTgtOGRjOS02ZmU4MWVkMzNhOTciLCJlbWFpbCI6Imthcm9seUBlYmkuYWMudWsiLCJuaWNrbmFtZSI6ImthcmVsIiwibmFtZSI6Ikthcm9seSBFcmRvcyIsImRvbWFpbnMiOlsiYWFwLXVzZXJzLWRvbWFpbiJdfQ.MnLeqmPdxGMy7ln3mlMFqhdNVDrf0uvilbe2pqngper56sjUYUOMnzvCK6ht2Q65P25VdJAA_nSOQJ03ZEqnp2ZB0urGpCY_sK0JV834ZSe1atLKww7wa2Ntq5EJakUfxrma9lHLTylGxJzYc3ej1s8pTE5Jj6tprvcV5s3eNEmYFUJL9RwhKmDA9-5E7TfOVYvEQSMw7IqXMiVSSQNU1o_dfalp-PYlqer9mTR2MPIMAaA2wdr7jKVDXzI7zKlprIRLVyJAiEPIeWzNYN8FC2RdigwqbcBt9UTTDrwDH5Op3fAJPrYWNpRD4-wV8mn5DWzd7cNm6dMqwm1C12WEg
....

NOTE: The token is valid for 1 hour.

== How to use the obtained token

IMPORTANT: You need to add this token as an `Authorization` header to all of your API requests.
The format is `Authorization: Bearer $TOKEN`

=== Example request
[source,bash]
----
 $ curl -i -X GET -H "Accept: application/hal+json" -H "Content-Type: application/hal+json" -H "Authorization: Bearer $TOKEN" https://submissionexampleurl.test.com/api/teams
----
== Don't copy and paste your token

You don't need to copy and paste the token. It's easier to write to an environment variable, such as in this example:

[source,bash,subs={markup-in-source}]
----
$ curl -u <your_aap_username>:<your_aap_password> {aapServerAPIRootURL}/auth > aap.jwt
$ TOKEN=`cat aap.jwt`
----

NOTE: If you don't login successfully, there will be an error message in `aap.jwt`, rather than a token.

You can then use the environment variable like this:

[source,bash]
----
 $ curl -i -X GET -H "Accept: application/hal+json" -H "Content-Type: application/hal+json" -H "Authorization: Bearer $TOKEN" https://submissionexampleurl.test.com/api/teams
----

Be careful with your token; anyone with it can act as if they are you.

== Teams, and why you need one

The submission system considers each piece of data to be owned by a team of people. This allows several people to
collaborate on submission, without sharing account details. You therefore need to create a team before you can work with
the submission API.

NOTE: What we call 'teams' are called 'domains' in the AAP documentation. This is because we use their domains to
represent groups of people working together, so team seemed like a more appropriate name.

== How to setup a team

To create a new team, send a `POST` request to the domains URL. The request body should be a
https://en.wikipedia.org/wiki/JSON[JSON document], with these fields:

 * `description` - a description of your team (optional)
 * `centreName` - name of your institute or project (required)

Creating a team will automatically make you a manager of that team, so you can add and remove people from it through the
AAP API or website.

=== Example request

include::{snippets}/create-team/curl-request.adoc[]

=== Example response

The response body will be a JSON document representing the team:

include::{snippets}/create-team/http-response.adoc[]

NOTE: You will need to request a new token before you can use the new team

== Managing your team

It is possible to add more people to the team. This is done through the AAP service.

=== How to add a user to a team

If you want to add a new user to a team, then you have to make a `PUT` request. To do this, you need to know two
identifiers - the user reference and the domain reference.

==== Finding your user reference

You can find the reference, if you know your username:

[source,bash,subs={markup-in-source}]
----
curl {aapServerAPIRootURL}/users/your-usename-goes-here -i -H "Authorization: Bearer $TOKEN"
----

The response should be a JSON document representing the user. It should include a field called `userReference`, with a
starting with `usr-`. This is the identifer you need.

==== Finding domain references

You can get a list of the teams you administer, such as the team you just created, with this request:

[source,bash,subs={markup-in-source}]
----
 $ curl {aapServerAPIRootURL}/my/management -i -H "Authorization: Bearer $TOKEN"
----

Alternatively, you can get a list of the teams you are a member of with this request:

[source,bash,subs={markup-in-source}]
----
 $ curl {aapServerAPIRootURL}/my/domains -i -H "Authorization: Bearer $TOKEN"
----

The response will be a list of domain documents. Each of these should have a field called `domainReference` - this is
the identifier you need. It should start with `dom-`.

==== Adding a user to a team

Once you have both identifiers, you can add the user to the team.

===== Example request

[source,bash,subs={markup-in-source}]
----
 $ curl '{aapServerAPIRootURL}/domains/<your_domain_reference>/<your_user_reference>/user' -i -X PUT -H "Authorization: Bearer $TOKEN" -H 'Accept: application/hal+json'
----

===== Example response

[literal,subs={markup-in-source}]
....
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
X-Application-Context: application:integration-test:0
Content-Type: application/hal+json;charset=utf-8
Content-Length: 1376

{
  "domainReference" : "dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80",
  "domainName" : "wonderland",
  "domainDesc" : "Drink me",
  "isActive" : "N",
  "users" : [ {
    "userReference" : "usr-d8749acf-6a22-4438-accc-cc8d1877ba36",
    "userName" : "karo",
    "email" : "karo@example.com",
    "mobile" : null,
    "domains" : null,
    "_links" : {
      "self" : {
        "href" : "{aapServerAPIRootURL}/users/usr-d8749acf-6a22-4438-accc-cc8d1877ba36"
      }
    }
  }, {
    "userReference" : "usr-9832620d-ec53-43a1-873d-efdc50d34ad1",
    "userName" : "ajay",
    "email" : "ajay@example.com",
    "mobile" : null,
    "domains" : null,
    "_links" : {
      "self" : {
        "href" : "{aapServerAPIRootURL}/users/usr-9832620d-ec53-43a1-873d-efdc50d34ad1"
      }
    }
  } ],
  "managers" : null,
  "_links" : {
    "self" : {
      "href" : "{aapServerAPIRootURL}/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80"
    },
    "deactivate" : {
      "href" : "{aapServerAPIRootURL}/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80"
    },
    "get users from domain" : {
      "href" : "{aapServerAPIRootURL}/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80/users"
    },
    "admin" : {
      "href" : "{aapServerAPIRootURL}/domains/dom-7c3aa7d3-e9bc-43e5-818a-8971390a3102"
    },
    "get all domains" : {
      "href" : "{aapServerAPIRootURL}/domains"
    }
  }
}
....

== You need to request a new token!

Each token includes all the details about who you are, and which teams you are a member of. You have now created a new
team and added yourself to it since you requested your first token, so that first token is out of date. You should
request a new one, as you did before. The new one will include the team you just created. You can use this new token
to access the submissions API.

== Wrapping up

You have now created an AAP account and team. You are now ready to log in to the submission API.

== Next steps

<<guide_getting_started.adoc#,Getting started>>
