= Samples
:docinfo: shared
:toc: auto
:nofooter:

== What are samples?

The definition of a sample is intentionally flexible in order to accommodate a wide range of uses. Typically, each
sample record corresponds to a discrete physical object that is composed of live biological material.

In most cases sample entities are self-evident; such as a blood sample, cell culture or an individual organism.
However, a sample can also be an environmental sample (e.g. for meta-genomic analysis), a hybrid between two species,
parasite infected cell culture, etc.

== Minimal requirements

These fields must be filled out for all samples:

* alias
* title
* releaseDate in YYYY-MM-DD format, e.g. `"2017-12-12"`

https://www.ebi.ac.uk/biosamples/[BioSamples] will release your sample information on or after the release date.

In addition, most of our data archives also require a taxonomy entry, to classify the species or sample type. This should
be given as a taxon ID. You can search for taxon IDs through the
https://www.ebi.ac.uk/ena/data/search?query=xenograft[ENA web page], or
https://www.ebi.ac.uk/ena/browse/taxonomy-service[API].

* taxonId

NOTE: Please note that not all taxon are considered acceptable for submitted data. For example
https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/tax-id/9443[primates] is not accepted, but
https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/tax-id/9606[humans] is.

== Optional fields

These fields are optional:

* description, a text description of the sample
* attributes, a structured description of the sample
* sampleRelationships,

=== Attributes

The attributes field should be structured like this:

.attributes
[source,javascript]
----
"attributes": {
    "<attribute name>": [
        "value": "<attribute value>",
        "units": "<units>",
        "terms": [
            {"url": "<Ontology term URL>"}
        ]
    ]
}
----


* value
* units, should specify the units used for a numeric value, e.g. to clarify if an age is specified in years, months, or
weeks. The unit should be lowercase and written out in full (e.g. "milimole" instead of "mm")
* terms, a list of ontology terms to describe the attribute. The url should be for an ontology term, available through
the https://www.ebi.ac.uk/ols[ontology lookup service]. E.g. "http://purl.obolibrary.org/obo/UBERON_0002114" for duodenum.

.example.attributes
[source,javascript]
----
"attributes": {
    "material": [
        "value": "specimen from organism",
        "terms": [
            {"url": "http://purl.obolibrary.org/obo/OBI_0001479"}
        ]
    ],
    "tissue": [
        "value": "stomach",
        "terms": [
            {"url": "http://purl.obolibrary.org/obo/UBERON_0000945"}
        ]
    ],
    "tissue weight": [
        "value": 907,
        "units": "gram"
    ]
}
----

=== Sample relationships

Sample relationships are used to record how samples are linked, e.g. parentage, or derivation

.relationships
[source,javascript]
----
"sampleRelationships": [
    {
        "alias": "<sample alias>",
        "relationshipNature": "<relationship nature>"
    }
]
----

These relationship natures are available:

* "derived from"
* "child of"
* "same as"
* "recurated from"

.relationship.example
[source,javascript]
----
"sampleRelationships": [
    {
        "alias": "sample-a-mum-1",
        "relationshipNature": "child of"
    },
    {
        "alias": "sample-a-dad-1",
        "relationshipNature": "child of"
    }
]
----

== Create a sample

=== Request

include::{snippets}/create-sample/curl-request.adoc[]


=== Response

include::{snippets}/create-sample/http-response.adoc[]

=== Links

include::{snippets}/create-sample/links.adoc[]


== Update a sample
=== Request

The user need to add the `accession` field to the request body, if the sample already exists in the archive.
If it only exists within the user's current draft submission, then the request body does not need it.

include::{snippets}/update-sample/curl-request.adoc[]

=== Response

include::{snippets}/update-sample/http-response.adoc[]

=== Links

include::{snippets}/update-sample/links.adoc[]

== Patch a sample
=== Request

The user need to add the `accession` field to the request body, if the sample already exists in the archive.
If it only exists within the user's current draft submission, then the request body does not need it.

include::{snippets}/patch-sample/curl-request.adoc[]

=== Response

include::{snippets}/patch-sample/http-response.adoc[]

=== Links

include::{snippets}/patch-sample/links.adoc[]