= Samples
:docinfo: shared
:toc: auto
:nofooter:

== What are samples?

The definition of a sample is intentionally flexible in order to accommodate a wide range of uses. Typically, each
sample record corresponds to a discrete physical object that is composed of live biological material.

In most cases sample entities are self-evident; such as a blood sample, cell culture or an individual organism.
However, a sample can also be an environmental sample (e.g. for meta-genomic analysis), a hybrid between two species,
parasite infected cell culture, etc.

https://www.ebi.ac.uk/biosamples/[BioSamples] will release your sample information on or after the given release date.

== Minimal requirements

These fields must be filled out for all samples:

* alias, unique name for the sample within the same team
* title, title of the sample
* releaseDate in YYYY-MM-DD format, e.g. `"2017-12-12"`

In addition, most of our data archives also requires organism information in the `taxon` field, to classify the species or sample type. This should
be given as a taxon ID (e.g. for human sample, "taxon:"9606"). The taxon IDs can be found in the
https://www.ebi.ac.uk/ols/ontologies/ncbitaxon[OLS organism classification], or the
https://www.ebi.ac.uk/ena/browse/taxonomy-service[ENA taxonomy service].

To search for taxon IDs use OLS-NCBI taxon or the https://www.ebi.ac.uk/ena/browse/taxonomy-service[ENA taxonomy service].


* taxonId

NOTE: Please note that not all taxon are considered acceptable for submitted data. For example
https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/tax-id/9443[primates] is not accepted, but
https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/tax-id/9606[humans] is.

== Optional fields

These fields are optional:

* description, a text description of the sample
* attributes, a structured description of the sample
* sampleRelationships, describe how various samples are linked together
* sampleExternalReferences, a list of external references of this sample
* checklistId, ID of an optional validation checklist to apply on the sample

=== Attributes

The attributes field should be structured like this:

.attributes
[source,javascript]
----
"attributes": {
    "<attribute name>": [
        "value": "<attribute value>",
        "units": "<units>",
        "terms": [
            {"url": "<Ontology term URL>"}
        ]
    ]
}
----


* value
* units, should specify the units used for a numeric value, e.g. to clarify if an age is specified in years, months, or
weeks. The unit should be lowercase and written out in full (e.g. "milimole" instead of "mm")
* terms, a list of ontology term URLs to describe the attribute. The url should be for an ontology term, available through
the https://www.ebi.ac.uk/ols[ontology lookup service]. E.g. "http://purl.obolibrary.org/obo/UBERON_0002114" for duodenum.

.example.attributes
[source,javascript]
----
"attributes": {
    "material": [
        "value": "specimen from organism",
        "terms": [
            {"url": "http://purl.obolibrary.org/obo/OBI_0001479"}
        ]
    ],
    "tissue": [
        "value": "stomach",
        "terms": [
            {"url": "http://purl.obolibrary.org/obo/UBERON_0000945"}
        ]
    ],
    "tissue weight": [
        "value": 907,
        "units": "gram"
    ]
}
----

=== Sample relationships

Sample relationships are used to record how samples are linked, e.g. parentage, or derivation

.relationships
[source,javascript]
----
"sampleRelationships": [
    {
        "alias": "<sample alias>",
        "relationshipNature": "<relationship nature>"
    }
]
----

These relationship natures are available:

* "derived from"
* "child of"
* "same as"
* "recurated from"

.relationship.example
[source,javascript]
----
"sampleRelationships": [
    {
        "alias": "sample-a-mum-1",
        "relationshipNature": "child of"
    },
    {
        "alias": "sample-a-dad-1",
        "relationshipNature": "child of"
    }
]
----

=== Sample external references

This part of the sample could contain a list of links to external resources.

.sample external reference example
[source,javascript]
----
  "sampleExternalReferences": [
    {
        "url" : "http://external.reference.com/ref1"
    },
    {
        "url" : "http://another.external.reference.com/ref2"
    }
]
----

=== ChecklistId

When submitting samples there is a minimal amount of information that is required (alias, title, release date).
Depending on the type of sample being described different communities having different requirements.
We call these additional requirements to checklist.

It is not mandatory to define a checklist to a sample. Currently you can only define one checklist to a sample.

.checklistid.example
[source,javascript]
----
"cheklistId": "ERC000021"
----


== Create a sample

=== Request

include::{snippets}/create-sample/curl-request.adoc[]


=== Response

include::{snippets}/create-sample/http-response.adoc[]

=== Links

include::{snippets}/create-sample/links.adoc[]


== Create a sample that comply with a given checklist

This is very similar to the default sample creation. It only differs by the added `checklistId` field in the request body.

=== Example Request

include::{snippets}/create-sample-with-checklistId/curl-request.adoc[]

=== Example Response

include::{snippets}/create-sample-with-checklistId/http-response.adoc[]

=== Links

include::{snippets}/create-sample-with-checklistId/links.adoc[]

== Create a sample with a sample external reference

This is very similar to the default sample creation. It only differs by the added `sampleExternalReferences` field in the request body.

=== Example request

include::{snippets}/create-sample-with-external-relationships/curl-request.adoc[]

=== Exanple response

include::{snippets}/create-sample-with-external-relationships/http-response.adoc[]


== Update a sample
=== Request

The user need to add the `accession` field to the request body, if the sample already exists in the archive.
If it only exists within the user's current draft submission, then the request body does not need it.

include::{snippets}/update-sample/curl-request.adoc[]

=== Response

include::{snippets}/update-sample/http-response.adoc[]

=== Links

include::{snippets}/update-sample/links.adoc[]

== Patch a sample
=== Request

The user need to add the `accession` field to the request body, if the sample already exists in the archive.
If it only exists within the user's current draft submission, then the request body does not need it.

include::{snippets}/patch-sample/curl-request.adoc[]

=== Response

include::{snippets}/patch-sample/http-response.adoc[]

=== Links

include::{snippets}/patch-sample/links.adoc[]
