= How to submit data programatically
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

== Overview

This document will take you through the steps required to submit descriptive data (often called "metadata") using the
https://www.ebi.ac.uk[EMBL-EBI] submission system. EMBL-EBI provide a https://en.wikipedia.org/wiki/HATEOAS[hypermedia]
https://en.wikipedia.org/wiki/Representational_state_transfer[REST API] to accept descriptive data from submitters using
standard HTTP requests.

The examples in this walkthrough use https://en.wikipedia.org/wiki/CURL[curl] to interact with the server, but you can
use the API with any programming language.

The submission process follows these steps:

 1. Create a submission
 2. Add documents describing your data to the submission (samples, studies, etc...)
 3. Get feedback and amend documents if necessary
 4. Tell us the submission is ready to go

At this point we will send the data to the appropriate archive or archives. They will send reports on their progress
with your data and accessions back to us.

This guide assumes some familiarity with REST APIs and the HTTP protocol.

== Authorization and authentication

This section describes how to get an authorisation token (AAP token) and what to do with it.

=== How to get a token

You can obtain a AAP token by executing the following curl command.

==== Example request

 $ curl -u <your_aap_username>:<your_aap_password> https://explore.api.aap.tsi.ebi.ac.uk/auth

The response will contains your AAP token. By default, the token is valid for 1 hour.

==== Example response

....
eyJhbGciOiWerFg78ghY.eyJpc3MiOiJodHRwhdsL3RzaS5lYmkuYWMudWsiLCJleHAiOjE1MDc4MjIxNzEsImp0aSI6IlNWUndCYWlubTA1MFlEZHJaWFRMbWciLCJpYXQiOjE1MDc4MTg1NzEsInN1YiI6InVzci0wZmRhM2YzZS0wM2I1LTQzOTgtOGRjOS02ZmU4MWVkMzNhOTciLCJlbWFpbCI6Imthcm9seUBlYmkuYWMudWsiLCJuaWNrbmFtZSI6ImthcmVsIiwibmFtZSI6Ikthcm9seSBFcmRvcyIsImRvbWFpbnMiOlsiYWFwLXVzZXJzLWRvbWFpbiJdfQ.MnLeqmPdxGMy7ln3mlMFqhdNVDrf0uvilbe2pqngper56sjUYUOMnzvCK6ht2Q65P25VdJAA_nSOQJ03ZEqnp2ZB0urGpCY_sK0JV834ZSe1atLKww7wa2Ntq5EJakUfxrma9lHLTylGxJzYc3ej1s8pTE5Jj6tprvcV5s3eNEmYFUJL9RwhKmDA9-5E7TfOVYvEQSMw7IqXMiVSSQNU1o_dfalp-PYlqer9mTR2MPIMAaA2wdr7jKVDXzI7zKlprIRLVyJAiEPIeWzNYN8FC2RdigwqbcBt9UTTDrwDH5Op3fAJPrYWNpRD4-wV8mn5DWzd7cNm6dMqwm1C12WEg
....

=== How to use the obtained token

You need to add this token as an `Authorization` header to all of your API requests.

==== Example request

 $ curl -i -X GET -H "Accept: application/hal+json" -H "Content-Type: application/hal+json" -H "Authorization: Bearer <your_aap_token>" https://submissionexampleurl.test.com/api/teams


=== How to setup a team

If you want to create a new team, then you have to send a `POST` request.

==== Example request

 $ curl 'https://explore.api.aap.tsi.ebi.ac.uk/domains' -i -X POST -H 'Content-Type: application/json;charset=UTF-8' -H 'Authorization: Bearer <your_aap_token>' -H 'Accept: application/hal+json' -d '{"domainName":"new domain","domainDesc":"new domain Desc"}'

==== Example response

....
HTTP/1.1 201 Created
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
X-Application-Context: application:integration-test:0
Content-Type: application/hal+json;charset=utf-8
Content-Length: 768

{
  "domainReference" : "dom-de00a819-dfe4-4516-8ad8-0c8d571e162d",
  "domainName" : "self.new domain",
  "domainDesc" : "new domain Desc",
  "isActive" : "Y",
  "users" : null,
  "managers" : null,
  "_links" : {
    "self" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-de00a819-dfe4-4516-8ad8-0c8d571e162d"
    },
    "deactivate" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-de00a819-dfe4-4516-8ad8-0c8d571e162d"
    },
    "get users from domain" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-de00a819-dfe4-4516-8ad8-0c8d571e162d/users"
    },
    "admin" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-eb5bd028-a4aa-45b9-9457-7c375b55d1b3"
    },
    "get all domains" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains"
    }
  }
}
....

=== How to add a user to a team

If you want to add a new user to a team, then you have to send a `PUT` request.

NOTE: In the above URL you have to prepend your user reference with `usr-` prefix.

// TODO: submit a bug for the AAP team to fix the above inconsistency and remove the note if they fixed it.

==== Example request

 $ curl 'http://explore.api.aap.tsi.ebi.ac.uk/domains/<your_domain_reference>/<your_user_reference>/user' -i -X PUT -H 'Authorization: Bearer <your_aap_token>' -H 'Accept: application/hal+json'

==== Example response

....
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
X-Application-Context: application:integration-test:0
Content-Type: application/hal+json;charset=utf-8
Content-Length: 1376

{
  "domainReference" : "dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80",
  "domainName" : "wonderland",
  "domainDesc" : "Drink me",
  "isActive" : "N",
  "users" : [ {
    "userReference" : "usr-d8749acf-6a22-4438-accc-cc8d1877ba36",
    "userName" : "karo",
    "email" : "karo@example.com",
    "mobile" : null,
    "domains" : null,
    "_links" : {
      "self" : {
        "href" : "http://explore.api.aap.tsi.ebi.ac.uk/users/usr-d8749acf-6a22-4438-accc-cc8d1877ba36"
      }
    }
  }, {
    "userReference" : "usr-9832620d-ec53-43a1-873d-efdc50d34ad1",
    "userName" : "ajay",
    "email" : "ajay@example.com",
    "mobile" : null,
    "domains" : null,
    "_links" : {
      "self" : {
        "href" : "http://explore.api.aap.tsi.ebi.ac.uk/users/usr-9832620d-ec53-43a1-873d-efdc50d34ad1"
      }
    }
  } ],
  "managers" : null,
  "_links" : {
    "self" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80"
    },
    "deactivate" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80"
    },
    "get users from domain" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-36ccaae5-1ce1-41f9-b65c-d349994e9c80/users"
    },
    "admin" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains/dom-7c3aa7d3-e9bc-43e5-818a-8971390a3102"
    },
    "get all domains" : {
      "href" : "http://explore.api.aap.tsi.ebi.ac.uk/domains"
    }
  }
}
....

== Fetch the API root

We recommend that you start from the root endpoint and follow the _links_ given in the `_links` section of the
response, instead of hard-coding each API endpoint. This will insulate you from future changes to the submission system
architecture or URL structure.

include::{snippets}/root-endpoint/curl-request.adoc[]

This will return a list of links, in http://stateless.co/hal_specification.html[HAL JSON] format:

include::{snippets}/root-endpoint/http-response.adoc[]

You don't need to worry about most of those links for now, we'll learn about them as we go.

== Create a submission

The submission system allows you to build up your submission and send it to the archives when you are ready.
The first step is to create a submission.

=== Pick a team

Every submission is owned by a _team_. A team is a group of people, working together on the same data. How you use this
is up to you. You could create a team for just yourself, everyone in a lab, or one for all collaborators on a project.

Teams are created and administed through the AAP system. TODO - link to AAP interface.

From the root endpoint, follow the link labelled `teams`:

include::{snippets}/get-teams/curl-request.adoc[]

This will show you the teams you a member of:

include::{snippets}/get-teams/http-response.adoc[]

=== POSTing a submission

Using the link labelled `submissions:create`, `POST` an empty document to create
a submission:

include::{snippets}/create-submission/curl-request.adoc[]

If successful, this will return a JSON object with links to parts of the submission:

include::{snippets}/create-submission/http-response.adoc[]



== Adding things to a submission

The next step is to follow the `contents` link from the submission. This will give you a set of links to get things in the
submission, or add things to it. The links returned will depend on how the server is configured, we don't expected to
support all data types.

include::{snippets}/submission-contents/curl-request.adoc[]

include::{snippets}/submission-contents/http-response.adoc[]

The response gives links to URLs where you can get all the items that are part of the submission, and links that you can
use when adding items to a submission (these end with `:create`).

ifdef::sample[]

We'll start by adding samples. It's a good template for adding anything to a submission - while the details in the
documents change, the process is the same across all types of document.

=== Naming samples (and everything else)

Samples, like all the documents that you add to a submission need to have an _alias_. This field is the name used for
the record within the submission system. Each alias should be unique within the records of that type owned by a team.
Using an alias for a second time in another submission will cause the record to be overwritten.

=== Requirements for sample documents

The description of a sample should normally include a taxonomic code to describe the species classification. This must
be an entry from the taxonomy database curated at https://www.ncbi.nlm.nih.gov/taxonomy/[NCBI]. EMBL-EBI provide a
http://www.ebi.ac.uk/ena/browse/taxonomy-service[service] to search for and look up taxonomic entries and this is used
when the submission system checks sample documents.

We will accept sample records for display in https://www.ebi.ac.uk/biosamples/[BioSamples] without a taxon ID, but
you will not be able to use the sample record when submitting data the experimental data archives without a taxon ID.
In addition, if you use a taxon ID, it must be one marked as 'submittable' in the taxonomy database.

=== POSTing a sample

Using the link from the submission labelled `samples:create` and `POST` a sample object:

include::{snippets}/create-sample/curl-request.adoc[]

This will return a response to show that the sample record has been created:

include::{snippets}/create-sample/http-response.adoc[]

endif::sample[]

=== Validation

Descriptive data is checked at two points during submission:

 1. When sent to the API server, through `POST`, `PUT` and `PATCH` requests. At this point the sent must be match the
 expected syntax, and be identified with an alias.
 2. Once accepted by the API server, it is sent to a suite of validators to ensure it meets the requirements of the
 relevant archives or project.

The second stage of validation is more in depth, and takes longer. Clients can poll for `ValidationResults` for each
submitted document, and for a submission. You will not be able to complete a submission until validation
has completed and errors have been found.

Use the `validationResult` link from sample (or any other submitted document) to see its validation results. This may be
 pending, in which case you can poll for completion.

include::{snippets}/get-validation-result/curl-request.adoc[]

include::{snippets}/get-validation-result/http-response.adoc[]


=== Updating a sample

If you want to change a sample record after you've created it, you should use a `PUT` request to replace the record:

include::{snippets}/update-sample/curl-request.adoc[]

include::{snippets}/update-sample/http-response.adoc[]

Updating a document will cause it to be re-validated, as described above.

ifdef::study[]

== Adding a study

Experimental data are grouped into _studies_. Studies should describe the motivation and summarise the design for the
study. Like samples, studies are identified by an alias, and have a number of attributes.

As with samples, study records are created using `POST` requests:

include::{snippets}/create-study/curl-request.adoc[]

This will return a response to show that the study record has been created:

include::{snippets}/create-study/http-response.adoc[]

endif::study[]

ifdef::assay[]

== Adding assays

Assay documents describes the processes performed on the sample to produce data. For example, this could be library
preparation and sequencing for an NGS study. If you are familiar with the ENA SRA submission system, an assay is equivalent to an Experiment.

include::{snippets}/create-assay/curl-request.adoc[]

This will return a response to show that the assay record has been created:

include::{snippets}/create-assay/http-response.adoc[]

endif::assay[]

ifdef::assayData[]

== Adding assay data

If you are familiar with the ENA SRA submission system, assay data is equivalent to a Run.

include::{snippets}/create-assay-data/curl-request.adoc[]

This will return a response to show that the assay record has been created:

include::{snippets}/create-assay-data/http-response.adoc[]

endif::assayData[]

== Finalising your submission

Once you have added all your documents to the submission and they have been validated, you can finalise it and send them
to the archives. You do this by changing the submission status. To get to the submission status, follow the
`submissionStatus` link from the submission, then the `self` link.

Follow the `availableStatuses` link from submission or submissionStatus to see the statuses that are currently available.
Available statuses are affected by whether or not validation has finished and the current status of the submission.

include::{snippets}/available-status-report/curl-request.adoc[]

This will return a response to show that the status can now be updated to 'Submitted':

include::{snippets}/available-status-report/http-response.adoc[]

You can change the submission status to 'Submitted', using either a `PUT` or `PATCH` request:

include::{snippets}/patch-submission-status/curl-request.adoc[]

This will return a response to show that the status has been changed:

include::{snippets}/patch-submission-status/http-response.adoc[]

This will also lock the submission, so you cannot make further changes while we broker the data into the archives.

== Tracking progress

Once you've finalised your submission, we will send it off to the relevant data archives. You can see how
that's progressing - e.g. has a study been received an accession yet?. There are several ways to do this.

Firstly, you can see the all details by following the `processingStatuses` link from the submission:

include::{snippets}/page-progress-reports/curl-request.adoc[]

include::{snippets}/page-progress-reports/http-response.adoc[]

You can also see summaries of the same information.

Summarised by status (follow the `processingStatusSummary` link from the submission):

include::{snippets}/summary-progress-reports/curl-request.adoc[]

include::{snippets}/summary-progress-reports/http-response.adoc[]

Summarised by status and type (follow the `typeProcessingStatusSummary` link from the submission)

include::{snippets}/type-summary-progress-reports/curl-request.adoc[]

include::{snippets}/type-summary-progress-reports/http-response.adoc[]

You can also follow the `processingStatus` link from sample (or any other part of the submission) to see the current
progress for an individual document.

== The end?

Once all documents in a submission have been completely archived, the submission is considered complete.

If you need to update the information of any of the records submitted, create an new submission and add a document,
following the same process as before. Using the same team and alias will ensure that the archive records are updated.

== When things go wrong

Successful requests will return a HTTP status code in `20X` range
(see the <<submission_api.adoc#_http_status_codes,reference docs>>). When something goes wrong, there will be an
error message to explain the problem. There's an explanation of each error type in the <<submission_api.adoc#_errors,reference docs>>.

Errors can normally be resolved by correcting the content or format of your request. Please get in touch if the cause
of the problem isn't clear or you need further assistance, by e-mailing our help desk - submission-help@ebi.ac.uk.

== Getting more information

You can find more in-depth documentation on the API in the <<submission_api.adoc#,reference documentation>>.

You can keep up to date with announcements about the submission system by subscribing to our mailing list.

You can subscribe by filling out the form link:https://listserver.ebi.ac.uk/mailman/listinfo/submission-announce[here].
